### ISSUE TITLE
Found a error when you type ' on the gamebanana search bar.

### ISSUE THREAD

**Issue by Nyanndev** [blueskythlikesclouds/DivaModLoader#10]
Only closing and reopening fixes the bug, the retry button doesn't do anything :[
![image](https://github.com/blueskythlikesclouds/DivaModLoader/assets/70298037/8de862d3-ef36-4686-8a86-197bb3feb923)

**Comment by blueskythlikesclouds** [comment]
Wrong project, ask it here: https://github.com/TekkaGB/DivaModManager
