### ISSUE TITLE
input lag after the update

### ISSUE THREAD

**Issue by 2Tiked8** [blueskythlikesclouds/DivaModLoader#16]
i updated the diva mod loader and after i open the game and there is input lag on any song (official and custom) i don't know how to resolve this, i tried the offset reset and other staff that the game offer but noting work, wnyone know how to resolve?

**Comment by blueskythlikesclouds** [comment]
Works on my machine. Maybe one of your mods causes it?

**Comment by 2Tiked8** [comment]
i tried to deselect evrything and reselecting but nothing, even with no mod the input lag don't go away

**Comment by blueskythlikesclouds** [comment]
So, is the lag still there when you uninstall the mod loader?

**Comment by blueskythlikesclouds** [comment]
Well?

**Comment by blueskythlikesclouds** [comment]
Figures.
