### ISSUE TITLE
File in tutorial doesn't exist

### ISSUE THREAD

**Issue by openuutau** [blueskythlikesclouds/DivaModLoader#17]
The dinput.dll doesn't exist. Also the tutorial is extremely hard to understand, I have no clue how to install it.

**Comment by nastys** [comment]
But it does exist
![Screenshot 2024-01-18 alle 08 33 49](https://github.com/blueskythlikesclouds/DivaModLoader/assets/7950891/64549e82-ed43-4d1f-acbe-3dde16e3db77)
The [README](https://github.com/blueskythlikesclouds/DivaModLoader) in the repository has very precise instructions, with a link to the Releases page
![Screenshot 2024-01-18 alle 08 34 37](https://github.com/blueskythlikesclouds/DivaModLoader/assets/7950891/2046f45c-79a6-42de-8395-ee4d5127c592)
![Screenshot 2024-01-18 alle 08 35 56](https://github.com/blueskythlikesclouds/DivaModLoader/assets/7950891/7e4d8604-7da0-46fd-851b-f9e44dc07acb)
