### ISSUE TITLE
Failed to load, Specified module not found

### ISSUE THREAD

**Issue by AK1NACH1RI** [blueskythlikesclouds/DivaModLoader#18]
Sorry if this isn't the right place to ask, but I figured I'd ask and be redirected if needed. These are from Eden Project, if that's a contributing factor.
Currently it won't load:
- LyricsPatch.dll
- SaveDataMigrator.dll
- OldMan.dll

I'm unsure if I need a specific plugin or not. I downloaded the one provided in the previous SongLimitPatch.dll issue, however it didn't fix these. I accidentally deleted a few plugins a bit ago, so I'm assuming that might be the issue. I don't know the specific ones I need to redownload though.

**Comment by blueskythlikesclouds** [comment]
I did not develop these mods, so I don't know. I assume you need Visual C++ redistributables though? 

https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

Install this and try again.

**Comment by AK1NACH1RI** [comment]
Sorry for a bit of a late reply, but thank you! I'm not good at tech whatsoever, so I was just puzzled.
