### ISSUE TITLE
If a large number of "Another Songs" are set, the song title will not be displayed.

### ISSUE THREAD

**Issue by enomoto-r02** [blueskythlikesclouds/DivaModLoader#21]
Nice to meet you, excuse me for the sudden request.

In Another Song, if there are nearly 10 Another Songs per song, some of them will be blank even if the Name name (name) and Change Vocals columns (vocal_disp_name) are set. (A similar phenomenon was observed in Japanese and English.)

I don't know if this is a problem with the game or with the DIVA MOD loader, but is it possible to fix it?

**Comment by enomoto-r02** [comment]
(postscript) Occurred when another_song.length=11 or greater. It doesn't happen with another_song.length=10.

**Comment by blueskythlikesclouds** [comment]
Are you sure this is not a PV DB sorting issue? Since if you go to 10, you'd need to sort like:

.0.
.1.
.10.
.2.
.3.

and on.

**Comment by enomoto-r02** [comment]
Oh my God, I was stupid. It worked perfectly. Thank you very much!
