### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by thibo1138** [blueskythlikesclouds/DivaModLoader#3]
Mod updating is failing after a json error
<img width="1099" alt="Capture d’écran 2022-07-24 à 16 16 25" src="https://user-images.githubusercontent.com/20288083/180651214-daefd920-7f77-41ca-9c31-9c94f72f753f.png">

I checked the targeted line but nothing seems wrong:
<img width="1121" alt="Capture d’écran 2022-07-24 à 16 23 21" src="https://user-images.githubusercontent.com/20288083/180651474-2dee0329-bb68-4ef3-a218-2fcd10e0fdd8.png">

An idea of what might cause the error?

**Comment by blueskythlikesclouds** [comment]
Wrong project, ask it here: https://github.com/TekkaGB/DivaModManager

**Comment by thibo1138** [comment]
Sorry my mistake
