### ISSUE TITLE
Failed to load SonglimitPatch.dll

### ISSUE THREAD

**Issue by dajiaquisba96385** [blueskythlikesclouds/DivaModLoader#4]
Please anything can help to solve this..I can't have song mod without it..thanks

**Comment by nastys** [comment]
This is unrelated to DivaModLoader.
Some plugins may require additional dependencies, such as Visual C++ Runtime 2022 x64.

**Comment by blueskythlikesclouds** [comment]
Yeah, I was gonna say.

**Comment by dajiaquisba96385** [comment]
Thank you guys, it solved by having some Visual C++

**Comment by blueskythlikesclouds** [comment]
Closing this, then.
