### ISSUE TITLE
Game not launching after 1.03 update with mods on Steam Deck

### ISSUE THREAD

**Issue by 2DGirl** [blueskythlikesclouds/DivaModLoader#6]
On Steam Deck, After 1.03 update, game refuses to launch before removing WINEDLLOVERRIDES='dinput8.dll=n,b' %command% in launch options, Any tips?

**Comment by blueskythlikesclouds** [comment]
Try disabling mods one by one and see which one crashes the game. This is not related to DML.

**Comment by 2DGirl** [comment]
you are right, song limit patch was a reason, sorry for bothering

**Comment by jozsefsallai** [comment]
FYI, new version of Song Limit Patch dropped earlier today which should work fine with 1.03: https://gamebanana.com/updates/186060
