### ISSUE TITLE
mod_pv_db.txt doesn't work on rom_steam_xx/rom

### ISSUE THREAD

**Issue by hiki8man** [blueskythlikesclouds/DivaModLoader#9]
I need use rom_steam_xx to supports game read different mod_pv_db on different language
but when i change my pv_db file name to mod_pv_db then game doesn't read mod_pv_db file
and when i change pv_db file name to mdata_pv_db, end_pv_db, patch_pv_db and patch2_pv_db, every thing work fine so i don't think it's because i put pv_db file in wrong folder
e.g
rom_steam_tw/rom/mod_pv_db.txt → doesn't work
rom_steam_tw/rom/patch2_pv_db.txt → work
(sorry i'm not good at english, maybe I didn't explain clearly)

**Comment by blueskythlikesclouds** [comment]
I getcha. I'll take a look at this when I have the opportunity.

**Comment by blueskythlikesclouds** [comment]
Fixed with DML v0.0.12 release.
